all:
  children:
    k8s-nodes:
      hosts:
        centos-vm1:
          iqn: iqn.1994-05.com.redhat:25eed2b03190 # arbitrary
        centos-vm2:
          iqn: iqn.1994-05.com.redhat:84fa2e8a357
        centos-vm3:
          iqn: iqn.1994-05.com.redhat:ff35376e1b0
        centos-vm4:
          iqn: iqn.1994-05.com.redhat:9284f3f7ccc0
        centos-vm5:
          iqn: iqn.1994-05.com.redhat:b49a3472e2
      vars:
        guest_user: kvm-user
