- name: make sure the remote host has directories for cloud-init
  file:
    path: '{{ item }}'
    owner: '{{ kvm_user }}'
    group: 'kvm'
    mode: '775'
    state: directory
  loop:
    - '/home/{{ kvm_user }}/cloud-init'
    - '/home/{{ kvm_user }}/cloud-init/{{ parent_item.instance_id }}'

- name: Extract xs archive
  shell: |
    IMG_DIR="{{ images_directory }}"
    COMPRESSED_FILE="$IMG_DIR/xz/{{ parent_item.image_filename }}"
    EXTRACTED_FILE="$IMG_DIR/{{ parent_item.instance_id }}.{{ parent_item.image_format }}"
    if [ -e "$EXTRACTED_FILE" ]; then
      echo "${EXTRACTED_FILE} already exists"
      exit 0
    fi
    echo "changed"
    unxz --stdout "$COMPRESSED_FILE" > "$EXTRACTED_FILE"
    chown {{ kvm_user }}:kvm "$EXTRACTED_FILE"
    chmod 775 "$EXTRACTED_FILE"
  register: result
  changed_when: result.stdout == "changed"
  failed_when: result.rc != 0

- name: Template cloud-init files
  template:
    src: 'cloud-init/{{ item }}.j2'
    dest: '/home/{{ kvm_user }}/cloud-init/{{ instance_id }}/{{ item }}'
    owner: '{{ kvm_user }}'
    group: 'kvm'
    mode: '644'
  vars:
    # expand here for documenting purpose
    instance_id: '{{parent_item.instance_id}}'
    local_hostname: '{{parent_item.local_hostname}}'
    user_name: '{{parent_item.user_name}}'
    plain_text_passwd: '{{parent_item.plain_text_passwd | default("")}}'
    device_name: '{{parent_item.network.device_name}}'
    addresses: '{{parent_item.network.addresses}}'
    gateway4: '{{parent_item.network.gateway4}}'
    nameservers: '{{parent_item.network.nameservers}}'
    # besides, ssh_authorized_keys are defined in variable root level
  register: ci_result
  loop:
    - meta-data
    - user-data
    - network-config

- name: Generate ISO image
  shell: |
    SRC_DIR='/home/{{ kvm_user }}/cloud-init/{{ parent_item.instance_id }}'
    DEST_FILE='{{ cloud_init_destination_dir }}/{{ parent_item.instance_id }}-seed.iso'
    if {{ ci_result.changed | lower }} ; then
      chattr –i "$DEST_FILE"
      rm "$DEST_FILE"
    fi
    if [ -e "$DEST_FILE" ]; then
      exit 0
    fi

    echo changed
    genisoimage --output "$DEST_FILE" -volid "cidata" -input-charset "utf-8" -joliet -rock \
      "$SRC_DIR/meta-data" "$SRC_DIR/user-data" "$SRC_DIR/network-config"
  register: result
  changed_when: result.stdout == "changed"

# - debug:
#     var: result

- name: Check disk size
  shell: "ls -hl {{ images_directory }}/{{ parent_item.instance_id }}.{{ parent_item.image_format }} | awk '{print $5}'"
  register: disk_size
  changed_when: False

- name: virtual_disk_size
  shell: "qemu-img info {{ images_directory }}/{{ parent_item.instance_id }}.{{ parent_item.image_format }} | grep 'virtual size' | sed -r 's|.*virtual size: ([0-9.]+) GiB.*|\\1G|'"
  register: virtual_disk_size
  changed_when: False

- debug:
    msg: |
      disk_size.stdout = {{ disk_size.stdout }}
      virtual_disk_size.stdout = {{ virtual_disk_size.stdout }}
      parent_item.disk_size = {{ parent_item.disk_size }}

- name: Resize image
  shell: qemu-img resize -f {{ parent_item.image_format }} {{ images_directory}}/{{ parent_item.instance_id }}.{{ parent_item.image_format }} {{ parent_item.disk_size }}
  when: disk_size.stdout != parent_item.disk_size and virtual_disk_size.stdout != "" and virtual_disk_size.stdout != parent_item.disk_size

- name: Generate Install Script for manual use
  template:
    src: virt-install.sh.j2
    dest: '/home/{{ kvm_user }}/cloud-init/{{ parent_item.instance_id }}/install.sh'
    owner: '{{kvm_user}}'
    group: 'kvm'
    mode: '774'

- name: Generate destroy script for manual use
  template:
    src: virt-destroy.sh.j2
    dest: '/home/{{ kvm_user }}/cloud-init/{{ parent_item.instance_id }}/destroy.sh'
    owner: '{{kvm_user}}'
    group: 'kvm'
    mode: '774'
