- name: Make sure the target dirs exist
  file:
    path: '{{ images_directory }}/xz'
    group: 'kvm'
    mode: '775'
    state: directory

- name: Copy Images
  copy:
    src: 'images/xz/{{ item.image_filename }}'
    dest: '{{ images_directory }}/xz/{{ item.image_filename }}'
    owner: '{{ kvm_user }}'
    group: kvm
  loop: '{{ guest_os_images }}'
