- name: Install KVM related packages
  ansible.builtin.apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-top
      - virt-manager
    state: present

- name: Enable libvirtd
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: yes
# - name: Add sudoers to allow ansible_user to run as KVM user
#   community.general.sudoers:
#     name: ansible_kvm
#     user: '{{ ansible_user }}'
#     runas: '{{ kvm_user }}'
