- name: Pre-check
  become: true
  import_tasks: pre-check.yml

- name: Install NVIDIA driver
  become: true
  import_tasks: nvidia.yml

- name: enable IOMMU
  become: true
  import_tasks: iommu.yml

- name: Install KVM
  become: true
  import_tasks: install.yml

- name: KVM User
  become: true
  import_tasks: user.yml

- name: Network Setting
  become: true
  import_tasks: network.yml

- name: Storage pool
  become: true
  import_tasks: pool.yml

- name: Prepare Qemu Hooks
  become: true
  import_tasks: qemu-hooks.yml

- name: Prepare Guest Images
  become: true
  import_tasks: guest-images.yml

- name: Prepare Guest Cloud-Init images
  become: true
  import_tasks: cloud-init.yml

- name: Prepare Guest Windows images
  become: true
  import_tasks: windows.yml
