# simply expanding / or mounting on /var would do
# - name: Mount disk to default image directory
#   ansible.posix.mount:
#     path: /var/lib/libvirt/images
#     src: '{{ kvm_image_volume_device }}'
#     fstype: ext4
#     state: mounted
#   when: kvm_image_volume_device is defined

# - name: modify pool dir
#   file:
#     path: /var/lib/libvirt/images
#     mode: '775'
#     owner: 'libvirt-qemu'
#     group: 'kvm'

# legacy install error for python-libvirt
# - name: virt pool
#   community.libvirt.virt_pool:
#     name: '{{ name }}'
#     autostart: yes
#     state: active
#     xml: '{{ lookup("template", "virt-pool-dir.xml.j2") }}'
#   vars:
#     name: '{{ default_virt_pool.name }}'
#     uuid: '{{ default_virt_pool.uuid }}'
#     path: '{{ default_virt_pool.path }}'

- name: check the pool
  become: true
  become_user: '{{ kvm_user }}'
  shell: |
    virsh pool-dumpxml --pool {{ default_virt_pool.name }} | grep '<path>/var/lib/libvirt/images</path>'
    virsh pool-list | grep '{{ default_virt_pool.name }}' | grep active | grep yes
  changed_when: False
