- hosts: all
  roles:
    - common

- hosts: dualboot
  roles:
    - dualboot

- hosts: nvidia
  roles:
    - nvidia

- hosts: ml
  roles:
    - ml
    - stable-diffusion

- hosts: kvm-hosts
  roles:
    - kvm
