all:
  hosts:
    kvm1:
      ansible_user: ubuntu
      kvm_user: kvm-user
      kvm_image_volume_device: /dev/sda1
      virt_pool_name: default
      network:
        bridge_name: br0
        interface_name: enp7s0
      guest_os_images:
        - url: https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-36-1.5.x86_64.raw.xz
          os_type: fedora-cloud
          image_name: Fedora-Cloud-Base-36-1.5.x86_64.raw
