all:
  hosts: {} # ungrouped hosts
  children:
    dualboot:
      hosts:
        ubuntu-gpu:
    kvm-hosts:
      hosts:
        kvm1:
    nvidia:
      hosts:
        kvm1:
        ubuntu-gpu:
    ml:
      hosts:
        ubuntu-gpu:
