all:
  hosts:
    kvm1:
      ansible_user: ubuntu
      kvm_user: kvm-user
      kvm_image_volume_device: /dev/sda1
      virt_pool_name: default
      network:
        bridge_name: br0
        interface_name: enp7s0
