- name: Add drivers
  become: true
  import_tasks: nvidia.yml

- name: Configure Git
  become: true
  import_tasks: git.yml

- name: Add machine learning prerequisites
  import_tasks: python.yml

- name: Stable Diffusion Pre
  become: true
  import_tasks: stable_diffusion_pre.yml

- name: Stable Diffusion
  import_tasks: stable_diffusion.yml
