guest_vms:
  windows:
    - instance_id: windows-vm1
      vnc_pass: password
  linux:
    - instance_id: centos-vm1
      local_hostname: centos-vm1
      noautoconsole: true
      image_filename: CentOS-Stream-GenericCloud-8-20220913.0.x86_64.qcow2.xz
      memory: '8192'
      vcpus: '2'
      image_format: qcow2
      disk_size: 50G
      os_variant: centos-stream8
      user_name: kvm-user
      network:
        device_name: eth0 # need to match
        addresses:
          - 10.10.10.111/255.255.255.0
        gateway4: '10.10.10.1'
        nameservers:
          - '10.10.10.1'
          - '8.8.8.8'
    - instance_id: centos-vm2
      local_hostname: centos-vm2
      noautoconsole: true
      image_filename: CentOS-Stream-GenericCloud-8-20220913.0.x86_64.qcow2.xz
      memory: '8192'
      vcpus: '2'
      image_format: qcow2
      disk_size: 50G
      os_variant: centos-stream8
      user_name: kvm-user
      network:
        device_name: eth0 # need to match
        addresses:
          - 10.10.10.112/255.255.255.0
        gateway4: '10.10.10.1'
        nameservers:
          - '10.10.10.1'
          - '8.8.8.8'
    - instance_id: centos-vm3
      local_hostname: centos-vm3
      noautoconsole: true
      image_filename: CentOS-Stream-GenericCloud-8-20220913.0.x86_64.qcow2.xz
      memory: '8192'
      vcpus: '2'
      image_format: qcow2
      disk_size: 50G
      os_variant: centos-stream8
      user_name: kvm-user
      network:
        device_name: eth0 # need to match
        addresses:
          - 10.10.10.113/255.255.255.0
        gateway4: '10.10.10.1'
        nameservers:
          - '10.10.10.1'
          - '8.8.8.8'
    - instance_id: centos-vm4
      local_hostname: centos-vm4
      noautoconsole: true
      image_filename: CentOS-Stream-GenericCloud-8-20220913.0.x86_64.qcow2.xz
      memory: '8192'
      vcpus: '2'
      image_format: qcow2
      disk_size: 50G
      os_variant: centos-stream8
      user_name: kvm-user
      network:
        device_name: eth0 # need to match
        addresses:
          - 10.10.10.114/255.255.255.0
        gateway4: '10.10.10.1'
        nameservers:
          - '10.10.10.1'
          - '8.8.8.8'
    - instance_id: centos-vm5
      local_hostname: centos-vm5
      noautoconsole: true
      image_filename: CentOS-Stream-GenericCloud-8-20220913.0.x86_64.qcow2.xz
      memory: '8192'
      vcpus: '2'
      image_format: qcow2
      disk_size: 50G
      os_variant: centos-stream8
      user_name: kvm-user
      network:
        device_name: eth0 # need to match
        addresses:
          - 10.10.10.115/255.255.255.0
        gateway4: '10.10.10.1'
        nameservers:
          - '10.10.10.1'
          - '8.8.8.8'
    - instance_id: ubuntu-gpu-kvm1
      local_hostname: ubuntu-gpu-kvm1
      passthrough_gpu: true
      disable_autostart: true
      noautoconsole: false
      image_filename: focal-server-cloudimg-amd64.img.xz
      memory: '8192'
      vcpus: '2'
      image_format: qcow2
      disk_size: 20G
      os_variant: ubuntu20.04
      user_name: kvm-user
      # plain_text_passwd: kvm-user
      network:
        device_name: enp1s0 # need to match
        addresses:
          - 10.10.10.121/24
        gateway4: '10.10.10.1'
        nameservers:
          - '10.10.10.1'
          - '8.8.8.8'
    # - instance_id: fedora-vm1
    #   local_hostname: fedora-vm1
    #   noautoconsole: true
    #   image_filename: Fedora-Cloud-Base-36-1.5.x86_64.raw.xz
    #   memory: '8192'
    #   vcpus: '2'
    #   image_format: raw
    #   disk_size: 50G
    #   os_variant: fedora-unknown
    #   user_name: kvm-user
    #   network:
    #     device_name: eth0 # need to match
    #     addresses:
    #       - 10.10.10.111/255.255.255.0
    #     gateway4: '10.10.10.1'
    #     nameservers:
    #       - '10.10.10.1'
    #       - '8.8.8.8'
