- name: Place network configuration file
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - src: 'netplan/99-custom.yaml.j2'
      dest: '/etc/netplan/99-ansible-custom.yaml'
  register: task_bridge

- name: Remove Installer network configs
  file:
    path: /etc/netplan/00-installer-config.yaml
    state: absent
  register: remove_init_config

- name: Apply netplan to see if the file is valid before reboot
  command: netplan apply
  when: task_bridge.changed or remove_init_config.changed

- name: Reboot if network configuration changed
  ansible.builtin.reboot:
    reboot_timeout: 100
  when: task_bridge.changed or remove_init_config.changed
# to inspect:
# cat /etc/network/interfaces
# networkctl
# ip address show br0
# brctl show
